theme: jekyll-theme-cayman
markdown: kramdown
plugins:
  - jekyll-toc

encoding: utf-8
timezone: Asia/Shanghai

kramdown:
  parse_block_html: true
  parse_span_html: true

toc:
  min_level: 1
  max_level: 3

defaults:
  - scope:
      path: ""
    values:
      toc: true