version: "3"
services:
  gitlab-ce:
    image: "$image_name"
    restart: always
    hostname: "$my_host"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://$myhost'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '/home/gitlab/config:/etc/gitlab'
      - '/home/gitlab/logs:/var/log/gitlab'
      - '/home/gitlab/data:/var/opt/gitlab'